@echo off
echo ========================
echo  BATCH VIDEO DOWNLOADER
echo ========================
echo.

:: Output directory
set "OUTPUT_FOLDER=C:\Users\PC\Downloads"

:: Global yt-dlp options
set "YTDLP_OPTIONS=--socket-timeout 60 --retries 30 --fragment-retries 30"

:: --------------------------------------------
:: Start downloading files one by one
:: --------------------------------------------


yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 02 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 02 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 02 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 03 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 03 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 03 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 03 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 04 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 04 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 04 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 04 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 05 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 05 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 05 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 05 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 06 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 06 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 06 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 06 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 07 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 07 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 07 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 07 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 08 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 08 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 08 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 08 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 09 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 09 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 09 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 09 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 10 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 10 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 10 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 10 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 11 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 11 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 11 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 11 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 12 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 12 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 12 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 12 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 13 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 13 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 13 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 13 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 14 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 14 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 14 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 14 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 15 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 15 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 15 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 15 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 16 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 16 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 16 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 16 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 17 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 17 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 17 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 17 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 18 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 18 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 18 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 18 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 19 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 19 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 19 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 19 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 20 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 20 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 20 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 20 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 21 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 21 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 21 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 21 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 22 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 22 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 22 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 22 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 23 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 23 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 23 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 23 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 24 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 24 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 24 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 24 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 25 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 25 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 25 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 25 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 26 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 26 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 26 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 26 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 27 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 27 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 27 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 27 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 28 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 28 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 28 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 28 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 29 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 29 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 29 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 29 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 30 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 30 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 30 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 30 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 31 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 31 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 31 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 31 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 32 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 32 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 32 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 32 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 33 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 33 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 33 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 33 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 34 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 34 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 34 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 34 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 35 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 35 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 35 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 35 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 36 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 36 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 36 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 36 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 37 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 37 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 37 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 37 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 38 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 38 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 38 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 38 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 39 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 39 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 39 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 39 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 70 -o "%OUTPUT_FOLDER%\Advanced Class - 40 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 66 -o "%OUTPUT_FOLDER%\Advanced Class - 40 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 62 -o "%OUTPUT_FOLDER%\Advanced Class - 40 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 57 -o "%OUTPUT_FOLDER%\Advanced Class - 40 720.mp4" ""



:: ... Continue for remaining videos ...

echo.
echo ========================
echo     ALL DOWNLOADS DONE!
echo ========================
pause
