@echo off
echo ========================
echo  BATCH VIDEO DOWNLOADER
echo ========================
echo.

:: Output directory
set "OUTPUT_FOLDER=C:\Users\PC\Downloads"

:: Global yt-dlp options
set "YTDLP_OPTIONS=--socket-timeout 60 --retries 30 --fragment-retries 30"

:: --------------------------------------------
:: Start downloading files one by one
:: --------------------------------------------


yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Calculation & Simplification 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Calculation & Simplification 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Calculation & Simplification 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Calculation & Simplification 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Calculation & Simplification 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Calculation & Simplification 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Calculation & Simplification 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Calculation & Simplification 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Calculation & Simplification 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Calculation & Simplification 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Calculation & Simplification 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Calculation & Simplification 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Calculation & Simplification 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Calculation & Simplification 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Calculation & Simplification 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Calculation & Simplification 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Calculation & Simplification 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Calculation & Simplification 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Calculation & Simplification 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Calculation & Simplification 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Calculation & Simplification 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Calculation & Simplification 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Calculation & Simplification 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Calculation & Simplification 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Calculation & Simplification 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Calculation & Simplification 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Calculation & Simplification 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Calculation & Simplification 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Calculation & Simplification 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Calculation & Simplification 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Calculation & Simplification 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Calculation & Simplification 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 13 Calculation & Simplification 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 13 Calculation & Simplification 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 13 Calculation & Simplification 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 13 Calculation & Simplification 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 14 Calculation & Simplification 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 14 Calculation & Simplification 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 14 Calculation & Simplification 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 14 Calculation & Simplification 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 15 Calculation & Simplification 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 15 Calculation & Simplification 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 15 Calculation & Simplification 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 15 Calculation & Simplification 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Surds & Indices 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Surds & Indices 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Surds & Indices 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Surds & Indices 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Co-ordinate Geometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Co-ordinate Geometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Co-ordinate Geometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Co-ordinate Geometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Co-ordinate Geometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Co-ordinate Geometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Co-ordinate Geometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Co-ordinate Geometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Co-ordinate Geometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Co-ordinate Geometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Co-ordinate Geometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Co-ordinate Geometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Co-ordinate Geometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Co-ordinate Geometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Co-ordinate Geometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Co-ordinate Geometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Co-ordinate Geometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Co-ordinate Geometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Co-ordinate Geometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Co-ordinate Geometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Co-ordinate Geometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Co-ordinate Geometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Co-ordinate Geometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Co-ordinate Geometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Co-ordinate Geometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Co-ordinate Geometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Co-ordinate Geometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Co-ordinate Geometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Co-ordinate Geometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Co-ordinate Geometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Co-ordinate Geometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Co-ordinate Geometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 01 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 02 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 03 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 04 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 05 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 06 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 07 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 08 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 09 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 10 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 11 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 12 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 13 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 13 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 13 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 13 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 14 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 14 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 14 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 14 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 15 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 15 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 15 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 15 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 16 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 16 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 16 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 16 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 17 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 17 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 17 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 17 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 18 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 18 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 18 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 18 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 19 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 19 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 19 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 19 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 20 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 20 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 20 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 20 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 21 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 21 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 21 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 21 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 22 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 22 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 22 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 22 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 23 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 23 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 23 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 23 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 24 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 24 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 24 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 24 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 25 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 25 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 25 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 25 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 26 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 26 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 26 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 26 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 27 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 27 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 27 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 27 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 28 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 28 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 28 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 28 Trigonometry 720.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 29 Trigonometry 240.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 99 -o "%OUTPUT_FOLDER%\Advanced Class - 29 Trigonometry 360.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 95 -o "%OUTPUT_FOLDER%\Advanced Class - 29 Trigonometry 480.mp4" ""
yt-dlp %YTDLP_OPTIONS% --concurrent-fragments 92 -o "%OUTPUT_FOLDER%\Advanced Class - 29 Trigonometry 720.mp4" ""


:: ... Continue for remaining videos ...

echo.
echo ========================
echo     ALL DOWNLOADS DONE!
echo ========================
pause
